name: TFE-JSONschema

on:
  workflow_dispatch:
  #schedule:
  #  - cron:  '0 10 * * *'


jobs:
  ConvertTFEStructs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.4'

      - name: Run
        run: |
          go run main

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}