name: TFE-JSONschema

on:
  workflow_dispatch:
  #schedule:
  #  - cron:  '0 10 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #  with:
      #    path: main

      #- name: Check hashicorp/go-tfe
      #  uses: actions/checkout@master
      #  with:
      #    repository: hashicorp/go-tfe
      #    path: go-tfe
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.4'

      - name: Run
        run: |
          go run main
          
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}